# group_vars/all.yml

# S3 버킷, 리전, 시크릿파일 경로
velero_bucket: velero-test-backup-325267459594-ap-northeast-2-an
velero_region: ap-northeast-2
velero_secret_file: /root/velero/credentials-velero

# AWS Credentials
aws_access_key_id: "YOUR_AWS_ACCESS_KEY_ID"
aws_secret_access_key: "YOUR_AWS_SECRET_ACCESS_KEY"

