---
- import_playbook: 00_precheck.yml
  tags: precheck
- import_playbook: 10_backup_acc_system.yml
  tags: backup
- import_playbook: 20_delete_acc_system.yml
  tags: delete
- import_playbook: 30_restore_acc_system.yml
  tags: restore
- import_playbook: 40_validate_acc_system.yml
  tags: validate
